# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='where',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out')], default='O', max_length=1),
        ),
    ]
