# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_where'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='seen',
            new_name='observed',
        ),
    ]
