# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerKnown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='last_modif_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='partnerknown',
            name='Partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner'),
        ),
    ]
