# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20170808_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerknown',
            name='Partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='seen',
            field=models.CharField(choices=[('N', 'None'), ('B', 'Boobs'), ('A', 'Ass'), ('P', 'Pussy'), ('M', 'Masturbating'), ('F', 'Fucking')], default='N', max_length=1),
        ),
        migrations.DeleteModel(
            name='PartnerKnown',
        ),
    ]
