# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20170809_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerKnown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.CharField(choices=[('N', 'None'), ('B', 'Boobs'), ('A', 'Ass'), ('P', 'Pussy'), ('M', 'Masturbating'), ('F', 'Fucking')], default='N', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='partner',
            name='seen',
        ),
        migrations.AddField(
            model_name='partnerknown',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner'),
        ),
    ]
