# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20170807_2138'),
        ('partners', '0004_auto_20170809_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonByPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personbyplace', to='partners.Partner')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personbyplace', to='places.Place')),
            ],
        ),
        migrations.AlterField(
            model_name='partnerknown',
            name='seen',
            field=models.CharField(choices=[('N', 'N...'), ('B', 'B...'), ('A', 'A...'), ('P', 'P...'), ('M', 'M...'), ('F', 'F...')], default='N', max_length=1),
        ),
    ]
