# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20170810_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerknown',
            name='seen',
            field=models.CharField(choices=[('N', 'N...'), ('B', 'B...'), ('A', 'A...'), ('P', 'P...'), ('M', 'M...'), ('F', 'F...'), ('P', 'P...'), ('V', 'V...')], default='N', max_length=1),
        ),
    ]
