# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20170811_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbyplace',
            name='seen',
            field=models.CharField(choices=[('B', 'B...'), ('F', 'F...'), ('P', 'P...'), ('E', 'E...'), ('C', 'C...'), ('S', 'S...'), ('F', 'F...'), ('W', 'SW...')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='partnerknown',
            name='seen',
            field=models.CharField(choices=[('B', 'B...'), ('A', 'A...'), ('P', 'P...'), ('M', 'M...'), ('F', 'F...'), ('P', 'P...'), ('V', 'V...')], max_length=1),
        ),
    ]
